name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Confirm GCP authentication
        run: gcloud auth list

      - name: Build Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/ubiquityml-landing .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ubiquityml-landing \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/ubiquityml-landing \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
